global:
  scrape_interval:     15s


scrape_configs:
  - job_name: 'rabbitmq'

    static_configs:
      - targets: ['rabbitmq:15692']
    
  - job_name: cadvisor
    scrape_interval: 5s

    static_configs:
    - targets: ['cadvisor:8080']