global:
  scrape_interval:     15s


scrape_configs:
  - job_name: 'rabbitmq'

    static_configs:
      - targets: ['rabbitmq:15692']
    
  - job_name: 'cadvisor'
    scrape_interval: 5s

    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwiZXhwIjo0OTA2MjYzNzExfQ.3LaClfXz30nvHD4qarBoXODZMK4aG96aj_xjeKm89FeS2TJd54oLTE1g3K_y-idZHsCifVX3lnCttAEau8ySOQ
    metrics_path: /minio/v2/metrics/cluster
    # scheme: http
    static_configs:
      - targets: ['${MINIO_HOST}:9000']